#!/usr/bin/python3
def findbig(x):
	i = 2
	while (i < x):
		if (x % i == 0):
			break
		i += 1
	j =  x / i
	return int(i), int(j)
def findfactor(x):
	x = int(x)
	if x > 10000:
		i, j = findbig(x)
		print(f"{x}={j}*{i}")
		return
	for i in range(2, x):
		for j in range(2, x):
			if (i * j == x):
				print(f"{x}={j}*{i}")
				return
if __name__ == "__main__":
	import sys
	liste = []
	with open(sys.argv[1]) as fi:
		for line in fi:
			i = line[:-1]
			findfactor(i)
